### ISSUE TITLE
Problem with NodeList in index.d.ts in node.js project

### ISSUE THREAD

**Issue by Gamadril** [ohmjs/ohm#220]
I have a node.js based TypeScript project. ohm is installed using npm. Running `tsc -p` throws an error:
`node_modules/ohm-js/index.d.ts(39,16): error TS2304: Cannot find name 'NodeList'.`

I guess because NodeList is browser specific. Commenting out the `grammarFromScriptElements` function signature in index.d.ts makes it compile again.

**Comment by pdubroy** [comment]
I'd like to improve our TypeScript support, so thanks for filing this. Could you share the compiler config you are using (e.g. `tsconfig.json`)?

**Comment by Gamadril** [comment]
sure. it's part of a VS Code extension, I'm currently working on.
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "outDir": "build",
        "lib": [
            "es6"
        ],
        "sourceMap": true,
        "noUnusedLocals": true,
        "strict": true
    },
    "exclude": [
        "node_modules",
        ".vscode-test"
    ]
}
```

**Comment by pdubroy** [comment]
Thanks. If you change your `"lib"` entry to have the value `["es6", "dom"]`, does that fix your problem?

I don't fully understand how TS resolves the types in this situation, but what happens if you add `/// <reference types="dom" />` to the top of Ohm's `index.d.ts` (and leave your `"lib"` entry as it is now)?

**Comment by Gamadril** [comment]
["es6", "dom"] seems to fix it, but it also affects the validation of the own project code.

Adding `/// <reference types="dom" />` leads to another error:
`node_modules/ohm-js/index.d.ts(1,23): error TS2688: Cannot find type definition file for 'dom'.`

![image](https://user-images.githubusercontent.com/3903793/39579831-f93c230e-4ee7-11e8-91bf-f57cd8655e87.png)

**Comment by pdubroy** [comment]
Hmm, ok. So for your use case, you'd prefer that the Ohm definitions don't refer to any types from the DOM library, right?

I think maybe the solution is to do something similar to what [ProtoBuf.js does](https://github.com/dcodeIO/ProtoBuf.js/): you should be able to choose to use a subset of the API that doesn't include any browser-related features. E.g., `import * as ohm from 'ohm-js/no-dom';`.

**Comment by Gamadril** [comment]
That would be great.

**Comment by Gamadril** [comment]
If you plan to make a separate version, consider updating the dependency list for node.js version. AFAIK "es6-symbol" and "is-buffer" are not necessary any more. Especially "es6-symbol" has other dependencies which are downloaded locally, but at lest in node.js case not necessary at all. "es5-ext" needs 3.5 MB of local space. In my case it becomes part of the VSCode extension and blows up the size of the extension.
