### ISSUE TITLE
Syntax error handling?

### ISSUE THREAD

**Issue by justinmchase** [ohmjs/ohm#466]
I'm looking at your error docs on syntax errors here:
https://github.com/ohmjs/ohm/blob/main/doc/errors.md#grammar-syntax-error

And it uses this example grammar:
```ohm
G {
  start = *x
}
```
With this error message
> Expected "~", "&", "#", an identifier, "\"", a number, "(", "[", "``", "{", "--", "|", or "}"

I'm wondering how syntax errors are calculated in general? As in, what is the strategy for determining the true error?

Could it simply be described as:

> A summary of all patterns which failed to match the _right-most_ position of the input?

From that right-most failure position how are you determining what was "expected"? When you have a complex set of rules parsing a position (and failing) are all failing patterns useful or only terminals?

**Comment by pdubroy** [comment]
Hi Justin! Yes, that's pretty much it.

For cleaner errors, it helps you to use _rule descriptions_ (e.g. `an identifier` or `a number`):

<img width="587" alt="CleanShot 2024-02-25 at 07 36 55@2x" src="https://github.com/ohmjs/ohm/assets/17293/535d9667-5a18-4d67-a07f-5f4c2a01eee9">

You can read more in https://github.com/ohmjs/ohm/issues/302.

**Comment by justinmchase** [comment]
thanks
